Basic imports and environment checks:
- PyTorch version verification is essential for reproducibility
- CUDA availability check - we'll need GPU access for future assignments
- If CUDA isn't available, try nvidia-smi in terminal to check GPU status

In [1]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.7.1
CUDA available: False


Converting Python list to tensor - torch.as_tensor() is preferred over torch.tensor()
as it can share memory with original data

In [2]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

tensor([1, 2, 3, 4, 5])


Creating zero-filled tensor - useful for initializing buffers or placeholder tensors

In [3]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Creating tensor filled with ones - commonly used for masks or initialization

In [4]:
x = torch.ones(3, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating tensor with custom fill value - useful when you need specific constant values

In [5]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


Random tensor from normal distribution - key for weight initialization

In [ ]:
x = torch.randn(3, 4)
print(t)

tensor([[-0.6750, -0.8546,  0.0194,  0.0653],
        [-0.6628,  0.7991,  1.3028,  0.9631],
        [ 0.6874, -2.4452, -1.8554, -0.4416]])


`zeros_like` creates tensor with same shape/dtype as input but filled with zeros

In [7]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


`ones_like` - similar to before but fills with ones

In [ ]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

`full_like` - creates tensor matching input shape but with custom fill value

In [8]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


`new_tensor` creates tensor with inherited properties (device/dtype) from source

In [ ]:
x = torch.zeros(3, 4, dtype=torch.bool)
y = x.new_tensor([1, 2, 3, 4])
print(y)

Broadcasting example with 2D tensors - shows automatic size matching

In [14]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(z, z.shape)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) torch.Size([5, 5])


Complex broadcasting with 5D tensors - demonstrates multi-dimension expansion

In [15]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

tensor([[[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]],



        [[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]]]) torch.Size([2, 1, 3, 1, 2])


Mean reduction - shows global and dimensional mean calculations

In [16]:
x = torch.ones(3, 4, 5)
print(x.mean())
print(x.mean(-1))

tensor(1.)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Sum reduction - demonstrates summing across specified dimensions

In [17]:
x = torch.ones(3, 4, 5)
print(x.sum(dim=0))
print(x.sum(dim=(1, 2)))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([20., 20., 20.])


`keepdim`` usage - shows difference in output shapes

In [18]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

tensor([20., 20., 20.]) torch.Size([3])
tensor([[[20.]],

        [[20.]],

        [[20.]]]) torch.Size([3, 1, 1])


Type conversion example - converting float tensor to long (int64)

In [19]:
x = torch.randn(5, 5)
print(x.to(torch.long))

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  1, -1, -1],
        [ 0,  0,  0,  0,  1],
        [ 0,  0,  1,  0,  0],
        [ 0,  0,  0,  1,  0]])


Reshaping with view - maintains underlying data pointer

In [24]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(2, -1)
print(y, y.shape)
print(z, z.shape)

tensor([[ 1.7153, -1.1574],
        [ 0.6433,  0.5930],
        [ 0.7129,  0.1161],
        [-0.5008,  0.0967],
        [ 0.9353,  0.1436],
        [ 0.5609,  0.4287]]) torch.Size([6, 2])
tensor([[ 1.7153, -1.1574,  0.6433,  0.5930,  0.7129,  0.1161],
        [-0.5008,  0.0967,  0.9353,  0.1436,  0.5609,  0.4287]]) torch.Size([2, 6])


Permute operation - reorders dimensions of tensor

In [58]:
x = torch.randn(2, 3, 2)
y = x.permute(1, 2, 0)
print(y, y.shape)

tensor([[[ 0.3272, -1.0295],
         [ 1.0499,  1.5242]],

        [[ 1.2812,  0.1551],
         [-0.4229,  0.5317]],

        [[ 0.0996,  0.1010],
         [ 0.6441,  1.6978]]]) torch.Size([3, 2, 2])


Concatenation along specified dimension

In [60]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=1)
print(z, z.shape)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) torch.Size([2, 6])


Stack operation - adds new dimension for combining tensors

In [62]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


Performance comparison: Python list operations vs PyTorch operations

In [63]:
import time


def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0394 sec.


PyTorch vectorized operation - significantly faster

In [64]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0052 sec.


Type conversion examples - showing different conversion methods

In [65]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

tensor([[ 0.2163,  2.2314, -0.7113],
        [ 0.8897,  0.8361, -1.2540],
        [-0.2362,  0.6597,  0.1507]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[ 0,  2,  0],
        [ 0,  0, -1],
        [ 0,  0,  0]])


`arange` examples - different ways to create sequences

In [66]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
tensor([3, 5, 7, 9])
